### ISSUE TITLE
Any known workaround for Mail in Yosemite?

### ISSUE THREAD

**Issue by lmartins** [nompute/GMailinator#12]
Im now running the public beta version.
Any workaround to reenable GMailinator in this version?

**Comment by nompute** [comment]
Mmm, don't have a system I can put the public beta on, but you could try running `find_uuid.sh` in the repo on your system, and see if any of the strings that pop up _don't_ exist in Info.plist, and add them under the `SupportedPluginCompatibilityUUIDs` key.

**Comment by lmartins** [comment]
Im afraid im not really sure about the steps for the actions you describe. Could you provide a little more detail please?

**Comment by nompute** [comment]
Try this:
1. Clone the project locally, and cd into the project folder.  Run `sh find_uuid.sh`.
2. Navigate to `/Users/myl/Library/Mail/Bundles/GMailinator.mailbundle/Contents`
3. Edit Info.plist, and add the UUIDs from the `find_uuid.sh` script into `SupportedPluginCompatibilityUUIDs`

**Comment by lmartins** [comment]
Awesome!! It works just fine after those changes.
Thanks man!
