### ISSUE TITLE
Add compatibility with Mail 7.1

### ISSUE THREAD

**Issue by Pe8er** [nompute/GMailinator#2]
The plugin no longer works, unfortunately.

**Comment by nompute** [comment]
I've just updated the latest build for 10.9.1 compatibility.  Let me know if you still have trouble (the comment for the Info.plist also includes commands to grab the latest UUIDs, just in case I'm running some odd build of OS X).

**Comment by Pe8er** [comment]
It works! Thank you so much. FYI I've got build 1CD40D64-945D-4D50-B12D-9CD865533506 -- 10.9.1, build 13B42. Came with the computer (newest iMac).
