### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by tsenart** [nompute/GMailinator#22]
Hello there!

I would like to use this Mail plugin but it doesn't seem to work with Yosemite. Can I provide any more info?

Thanks

**Comment by matellis** [comment]
This worked for me. Good luck!
1. Move your Gmailinator bundle into `/Library/Mail/Bundles` (you may have to create the `Bundles` folder).
2. Open a terminal session and type the following:
   
   ```
   defaults read /Applications/Mail.app/Contents/Info PluginCompatibilityUUID
   ```
3. Open the file `/Library/Mail/Bundles/GMailinator.mailbundle/Contents/Info.plist`
4. At the bottom of the file you file find a section that looks like this:
   
   ```
   <array>
           <string>DAFFB2B4-77BC-4C25-8CE1-2405E652D54B</string>
           <string>2B98D2DD-000B-4521-83EB-7BFCB9B161C8</string>
           <string>608CE00F-4576-4CAD-B362-F3CCB7DE8D67</string>
           <string>1146A009-E373-4DB6-AB4D-47E59A7E50FD</string>
           <string>2183B2CD-BEDF-4AA6-AC18-A1BBED2E3354</string>
           <string>19B53E95-0964-4AAB-88F9-6D2F8B7B6037</string>
           <string>0941BB9F-231F-452D-A26F-47A43863C991</string>
           <string>04D6EC0A-52FF-4BBE-9896-C0B5FB851BBA</string>
           <string>FBE5B158-5602-4A6D-9CC5-8461B9B7054E</string>
           <string>1CD40D64-945D-4D50-B12D-9CD865533506</string>
           <string>88ED2D4C-D384-4BF5-8E94-B533455E6AAF</string>
           <string>F4C26776-22B3-4A0A-96E1-EA8E4482E0B5</string>
           <string>D1EFE124-86FF-4751-BF00-80B2C0D6F2E4</string>
   </array>
   ```
5. Take the value it outputs (which should be something like `800E5C92-87D3-429B-8740-5C6183CD13EA`) and add it to the end of the list of values, so it looks like this:
   
   ```
     <array>
         <string>DAFFB2B4-77BC-4C25-8CE1-2405E652D54B</string>
         <string>2B98D2DD-000B-4521-83EB-7BFCB9B161C8</string>
         <string>608CE00F-4576-4CAD-B362-F3CCB7DE8D67</string>
         <string>1146A009-E373-4DB6-AB4D-47E59A7E50FD</string>
         <string>2183B2CD-BEDF-4AA6-AC18-A1BBED2E3354</string>
         <string>19B53E95-0964-4AAB-88F9-6D2F8B7B6037</string>
         <string>0941BB9F-231F-452D-A26F-47A43863C991</string>
         <string>04D6EC0A-52FF-4BBE-9896-C0B5FB851BBA</string>
         <string>FBE5B158-5602-4A6D-9CC5-8461B9B7054E</string>
         <string>1CD40D64-945D-4D50-B12D-9CD865533506</string>
         <string>88ED2D4C-D384-4BF5-8E94-B533455E6AAF</string>
         <string>F4C26776-22B3-4A0A-96E1-EA8E4482E0B5</string>
         <string>D1EFE124-86FF-4751-BF00-80B2C0D6F2E4</string>
         <string>800E5C92-87D3-429B-8740-5C6183CD13EA</string>
     </array>
   ```
6. Save the file.
7. Run this command if you haven't already:
   
   ```
   defaults write com.apple.mail EnableBundles -bool true
   ```
8. Close terminal, start Mail. You should be working now.

**Comment by tsenart** [comment]
Works like a charm! But this should be done in the repo itself and packaged as a release :-) Thanks!

**Comment by nompute** [comment]
Took a while for me to get around to upgrading my system to Yosemite, but now that it is, I've bundled things up and [pushed a new release](https://github.com/nompute/GMailinator/releases/tag/0.10.0).  Thanks to everyone for helping to get new users up and running :)

**Comment by quicksketch** [comment]
Just did this yesterday, the latest release works great. Thanks @nompute!

**Comment by duff** [comment]
This project is wonderful.  Thanks so much @nompute!

Working great on Yosemite.

**Comment by matellis** [comment]
60D52D22-7491-4CA7-95BA-88215BD88F8E for Mail 8.2 (10.10.2)

**Comment by blakeperdue** [comment]
Awesome, this still works with Mail 9.3 on El Capitan.
