### ISSUE TITLE
Support for Mail.app 8.1

### ISSUE THREAD

**Issue by romanrev** [nompute/GMailinator#27]
Looks like the plugin is not compatible with the latest Mail.app after the Apple update: ![gmailinator incompatible with mail app 8 1](https://cloud.githubusercontent.com/assets/2794589/5135583/fd19324c-716d-11e4-9d98-102f5e4cf332.png)

**Comment by duff** [comment]
Hi @romanrev,

There is a pull request here you could pull into your own repo if you'd like to get it before it happens in master:

https://github.com/nompute/GMailinator/pull/26

**Comment by nompute** [comment]
Latest Mail.app UUID has been merged in, I'll cut a new binary release soon/
