### ISSUE TITLE
Mail.app Version 7.2 (1874) 

### ISSUE THREAD

**Issue by arunagw** [nompute/GMailinator#3]
Thanks for awesome plugin.

Any plans for Version 7.2 (1874) ?

**Comment by nompute** [comment]
Absolutely, just haven't had a chance to install the latest and greatest + create a new build.  Expect one within the next day or so.

**Comment by arunagw** [comment]
Awesome <3

**Comment by nompute** [comment]
Alright, new version uploaded to the repo!
