### ISSUE TITLE
OS Mail update breaks the plug-in!

### ISSUE THREAD

**Issue by jegirard** [nompute/GMailinator#47]
Not sure if this project is still alive, but the latest Mac OS update killed the plug-in... Would love to see if it could be updated, and would be happy to help if I can (don't have a ton to offer, but might be able to at least contribute $)!

-John

**Comment by acrollet** [comment]
FYI https://github.com/fikovnik/GMailinator is being kept up to date and works on high sierra - perhaps @nompute could link to it in the README?

**Comment by jegirard** [comment]
Great thank you!
