### ISSUE TITLE
Build Failing for Mail 12

### ISSUE THREAD

**Issue by lasthalf** [nompute/GMailinator#48]
Any ideas as to how to get this working in Mail 12? It seems the project is not able to alter any of the folders in `/Library/Mail`. I realize we're still in beta, but curious if this is being looked at yet. Thanks!

**Comment by flowerornament** [comment]
I'm not sure if this might not work for some reason, but I was able to build to the "Products" directory and manually move the bundle to `~/Library/Mail`.

Still, my build didn't work. Some things I tried:
- Adding a new SupportedPluginCompatabilityUUID as per previous instructions
- Building for OS 10.14
- Signing the build
- Giving the executable permissions via Security & Privacy / Privacy / Full Disk Access
- Enabling the plugin in settings (https://forums.developer.apple.com/thread/106856)

**Comment by jegirard** [comment]
Not sure why this is the case in Mail 12 when it wasn’t earlier, but it’s a System Integrity Protection issue. I was able to fix it by disabling SIP (be cautious) here: 

https://www.google.com/amp/s/www.imore.com/how-turn-system-integrity-protection-macos%3famp

You *should* be able to disable SIP, build, then re-enable SIP.

I didn’t have time to troubleshoot why my final build didn’t work, BUT I was able to get past the write permission issue using this approach. 

- John

**Comment by ashcreighton** [comment]
I tried the solution provided by @jegirard but still cannot get this to work.

It worked great for me on High Sierra, but upgrading to Mojave disabled it, and I can't seem to reinstall...

Any other solutions? I sure loved using this... 😭

**Comment by gmaclennan** [comment]
I finally got this working by trying lots of different things on a fresh install of MacOS Mojave 10.14.6 with Mail.app v 12.4.

I used [rbdr's fork](https://github.com/rbdr/gmailinator). The build failed with an error trying to move the built file into `~/Library/Mail/Bundles` but I moved it manually.

I ran `defaults write com.apple.mail EnableBundles -bool true` but when I opened Mail.app I didn't see any button to "Manage Plug-ins..." in the Preferences --> General pane.

I ran `sudo defaults write "/Library/Preferences/com.apple.mail" EnableBundles 1` and restarted Mail, and this time finally saw the button "Manage Plug-ins...". I clicked that button and activated GMailinator, and then restarted Mail.app... it worked! 

Hope this helps someone else.

**Comment by jriely** [comment]
Thanks @gmaclennan 
It worked for me!

**Comment by flowerornament** [comment]
Thank you @gmaclennan!

**Comment by mjabdulm** [comment]
Hi @gmaclennan 


> I finally got this working by trying lots of different things on a fresh install of MacOS Mojave 10.14.6 with Mail.app v 12.4.
> 
> I used [rbdr's fork](https://github.com/rbdr/gmailinator). The build failed with an error trying to move the built file into `~/Library/Mail/Bundles` but I moved it manually.
> 

Looks like rbdr's fork is not available anymore. Could you please share the bundle?

Thanks,
Abdul

**Comment by mjabdulm** [comment]
I got it working after adding my UUID to <key>SupportedPluginCompatibilityUUIDs</key>
  <array>
